[control_plane]
ubuntu-1 ansible_host=192.168.1.234 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/vm100_key

[workers]
# worker1 ansible_host=192.168.1.xxx ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/vm100_key

[k8s_cluster:children]
control_plane
workers

[pve_host]
pve ansible_host=192.168.1.94 ansible_user=ksh ansible_connection=local
