apiVersion: v1
kind: Service
metadata:
  name: vllm
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: vllm
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      nodePort: 30800
